kind: BuildConfig
apiVersion: v1
metadata:
  name: edge-anki-controller-dev
  labels:
    name: edge-anki-controller-dev
spec:
  triggers:
  - type: GitHub
    github:
      secret: CHANGEME
  - type: Generic
    generic:
      secret: CHANGEME
  - type: ConfigChange
  runPolicy: Serial
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('maven') {
          stage 'deploy'
          openshiftBuild(buildConfig: 'edge-anki-controller-deploy', showBuildLogs: 'true', namespace: 'edge-dev')
        }

