version: "2"

services:

  # car 1
  edge-anki-controller-1:
    image: sappelt/edge-anki-controller
    restart: unless-stopped
    network_mode: "host"
    environment:
      - HTTP_ADAS_WEBSOCKET=__HOSTNAME__:8003
      - HTTP_TWIN_WEBSOCKET=__HOSTNAME__:8001
      - CAR_NO=1
      - CAR_INIT_BLUETOOTH_ID=ec7d32207f95
      - CAR_LANE_NO=1
      - TRACK_CONFIG=config/eight-i3.json
    volumes:
      - car1config:/usr/src/app/mounted-config

  # car 2
  edge-anki-controller-2:
    image: sappelt/edge-anki-controller
    restart: unless-stopped
    network_mode: "host"
    environment:
      - HTTP_ADAS_WEBSOCKET=__HOSTNAME__:8003
      - HTTP_TWIN_WEBSOCKET=__HOSTNAME__:8001
      - CAR_NO=2
      - CAR_INIT_BLUETOOTH_ID=edef582991e2
      - CAR_LANE_NO=4
      - TRACK_CONFIG=config/eight-i3.json
    volumes:
      - car2config:/usr/src/app/mounted-config
 
  edge-anki-adas:
    image: sappelt/edge-anki-adas
    network_mode: "host"
    restart: unless-stopped
    environment:
      - CAR_HTTP_SERVER=__HOSTNAME__

  edge-anki-twin:
    image: sappelt/edge-anki-twin
    network_mode: "host"
    restart: unless-stopped
    environment:
      - CAR_HTTP_SERVER=__HOSTNAME__

  portainer:
    image: portainer/portainer
    container_name: "portainer-app" 
    network_mode: host
    volumes:
      - unix_sock:/var/run

volumes:
   car1config:
   car2config:
   unix_sock:
     driver_opts:
        type: none
        device: /var/run 
        o: bind
