kind: BuildConfig
apiVersion: v1
metadata:
  name: edge-anki-twin-dev
  labels:
    name: edge-anki-twin-dev
spec:
  triggers:
  - type: GitHub
    github:
      secret: CHANGEME
  - type: Generic
    generic:
      secret: CHANGEME
  - type: ConfigChange
  runPolicy: Serial
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('maven') {
          stage('build') {
            try {
              openshiftBuild(buildConfig: 'edge-anki-twin-build', showBuildLogs: 'true', namespace: 'edge-dev')
            } catch(e) {
              hipchatSend(color: 'RED', message: "Jenkins pipleine ${env.JOB_NAME} [${env.BUILD_NUMBER}] failed in stage edge-anki-objectdetection-build, please check: <a href='${env.BUILD_URL}'>here</a>")
              throw (e)
            }
          }
          stage('push') {
            try {
              openshiftBuild(buildConfig: 'edge-anki-twin-push', showBuildLogs: 'true', namespace: 'edge-dev')
            } catch(e) {
              hipchatSend(color: 'RED', message: "Jenkins pipleine ${env.JOB_NAME} [${env.BUILD_NUMBER}] failed in stage edge-anki-objectdetection-push, please check: <a href='${env.BUILD_URL}'>here</a>")
              throw (e)
            }
          }
          stage('notify') {
            hipchatSend(color: 'GREEN', message: "Jenkins pipleine ${env.JOB_NAME} [${env.BUILD_NUMBER}] completed successfully")
          }
        }

