kind: BuildConfig
apiVersion: v1
metadata:
  name: __NAME__
  labels:
    name: __NAME__
spec:
  triggers:
  - type: GitHub
    github:
      secret: CHANGEME
  - type: Generic
    generic:
      secret: CHANGEME
  - type: ConfigChange
  runPolicy: Serial
  strategy:
    type: Custom
    customStrategy:
      exposeDockerSocket: true
      forcePull: true
      from:
        kind: "DockerImage"
        name: "okoeth/edge-deployer"
      env:
        - name: COMMAND
          value: __COMMAND__
        - name: SERVER
          value: __SERVER__
        - name: TENANT
          value: __TENANT__
        - name: USER
          value: __USER__
        - name: PASSWORD
          value: __PASSWORD__
        - name: SERVICE_NAME
          value: __SERVICE_NAME__
        - name: SERVICE_TEMPLATE_ID
          value: __SERVICE_TEMPLATE_ID__
        - name: NETWORK_ID
          value: __NETWORK_ID__
        - name: SITE_GROUP_ID
          value: __SITE_GROUP_ID__
