kind: BuildConfig
apiVersion: v1
metadata:
  name: edge-anki-adas-prod
  labels:
    name: edge-anki-adas-prod
spec:
  triggers:
  - type: GitHub
    github:
      secret: CHANGEME
  - type: Generic
    generic:
      secret: CHANGEME
  - type: ConfigChange
  runPolicy: Serial
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('maven') {
          stage 'buildpush'
          openshiftBuild(buildConfig: 'edge-anki-adas-buildpush', showBuildLogs: 'true', namespace: 'edge-prod')
          stage 'deploy'
          openshiftBuild(buildConfig: 'edge-anki-adas-deploy', showBuildLogs: 'true', namespace: 'edge-prod')
        }

